name: Build Weekly Spotify Playlist

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-weekly-spotify-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install Pillow

      - name: Create weekly playlists for all users
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

          SPOTIFY_USER_REFRESH_TOKEN_HENRY_JOHNSON: ${{ secrets.SPOTIFY_USER_REFRESH_TOKEN_HENRY_JOHNSON }}
          SPOTIFY_USER_REFRESH_TOKEN_RAY_JOHNSON: ${{ secrets.SPOTIFY_USER_REFRESH_TOKEN_RAY_JOHNSON }}
          SPOTIFY_USER_REFRESH_TOKEN_PENNY_JOHNSON: ${{ secrets.SPOTIFY_USER_REFRESH_TOKEN_PENNY_JOHNSON }}
        run: python scripts/create_weekly_playlist.py
